### ISSUE TITLE
auth method outdated and depends on ssl lib, string isNil is not recommend for current nim version

### ISSUE THREAD

**Issue by bung87** [wiml/nim-asyncmysql#1]
not known the maintainence state, just note here in case somebody interested .

**Comment by wiml** [comment]
Thanks for the note. I'll see if I can bring this library up to date, but it is basically unmaintained — I don't use MySQL *or* Nim very much right now.

**Comment by bung87** [comment]
there's https://github.com/tulayang/asyncmysql which also implemented mysql connection protocol, async procs, auth methods, but it lack of ssl layer, afaik it is closest one in nim to the same goal, maybe you interested.

**Comment by wiml** [comment]
I have incorporated part of that PR and done some other modernization.

I've opened a separate issue (#3) for the rest of your PR
